### ISSUE TITLE
LinuxでSeeedJP STM32 Boardsのボードマネージャインストールに失敗する

### ISSUE THREAD

**Issue by ushiboy** [SeeedJP/Arduino_Core_STM32#1]
**症状**

http://www.seeed.co.jp/package_SeeedJP_index.json をボードマネージャのURLに追加したArduino IDE で SeeedJP STM32 Boards バージョン 1.3.0 のインストールに失敗します。

失敗時のエラーの内容は次のとおりです。

```
CRCが一致しません。ファイルが壊れています。一時的な問題かもしれませんので、もう一度試してみてください。
java.lang.RuntimeException: java.lang.Exception: CRCが一致しません。ファイルが壊れています。一時的な問題かもしれませんので、もう一度試してみてください。
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: CRCが一致しません。ファイルが壊れています。一時的な問題かもしれませんので、もう一度試してみてください。
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:105)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:113)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
```

調べて見たところ、779,780行目と786,787行目に誤りがありました。

- openocd-0.10.0.zip のMD5チェックサム
    - 正: e2b41d2279b08fb002ecfd13c8764725
    - 誤: 3648e4cd6af88ae4e3a59e068723a1d7
- openocd-0.10.0.zip のファイルサイズ
    - 正: 2784537
    - 誤: 10406262

差分は次のとおりです。
```
--- a/package_SeeedJP_index.json
+++ b/package_SeeedJP_index.json
@@ -776,15 +776,15 @@
               "host": "i686-linux-gnu",
               "url": "https://azureboard.blob.core.windows.net/toolchain/openocd-0.10.0.zip",
               "archiveFileName": "openocd-0.10.0.zip",
-              "checksum": "MD5:3648e4cd6af88ae4e3a59e068723a1d7",
-              "size": "10406262"
+              "checksum": "MD5:e2b41d2279b08fb002ecfd13c8764725",
+              "size": "2784537"
             },
             {
               "host": "x86_64-pc-linux-gnu",
               "url": "https://azureboard.blob.core.windows.net/toolchain/openocd-0.10.0.zip",
               "archiveFileName": "openocd-0.10.0.zip",
-              "checksum": "MD5:3648e4cd6af88ae4e3a59e068723a1d7",
-              "size": "10406262"
+              "checksum": "MD5:e2b41d2279b08fb002ecfd13c8764725",
+              "size": "2784537"
             },
             {
               "host": "i686-mingw32",
```

**環境**

- OS: ubuntu 18.04 (64bit)
- Arduino IDE 1.8.12

**Comment by matsujirushi** [comment]
@ushiboy 
ご連絡ありがとうございます。
SeeedJP STM32 Boardsは、現状、Linux環境をサポートしていません。
ただし、レポートいただければ極力反映いたしますので、今後もよろしくお願い致します。

アップデートしたjsonファイルを用意しました。
64bit linuxのArduino IDEでインストールできるところまでは確認しました。
恐れ入りますが、そちらでご確認いただけませんか？
よろしくお願い致します。

https://www.seeed.co.jp/package_SeeedJP1_index.json

**Comment by ushiboy** [comment]
@matsujirushi 
ご対応ありがとうございます。

ご指定のURLのJSONでボードマネージャのインストール、
およびスケッチのビルドとボードへの書き込みまで無事成功することを確認しました。

**Comment by matsujirushi** [comment]
> 本番リリース。
> https://www.seeed.co.jp/package_SeeedJP_index.json

**Comment by matsujirushi** [comment]
@ushiboy 
どうもありがとうございました。
